CheckInternalHash: false
CheckInternal: true
IgnoreDirectoryMissingTrailingSlash: true
CheckScripts: false
IgnoreAltMissing: true
IgnoreURLs:
  - "gips-framework.org"
HTTPHeaders:
  "User-Agent": "chrome"
  "accept-encoding": "deflate"
