CheckInternalHash: false
CheckInternal: true
IgnoreDirectoryMissingTrailingSlash: true
CheckScripts: false
IgnoreAltMissing: true
IgnoreURLs:
  - "gips.dev"
HTTPHeaders:
  "User-Agent": "chrome"
  "accept-encoding": "deflate"
